config/routes.rb
Rails.application.routes.draw do
  post '/votes/:vote_type/:item_type/:item_id/:short', to: "votes#create", as: "votes"
  delete '/votes/:vote_type/:item_type/:item_id/:short', to: "votes#destroy", as: "vote"
  
  resources :invitations
  get "/accept-invitation/:id/:password_token", to: "invitations#accept", as: "accept_invitation"
  get "/decline-invitation/:id/:password_token", to: "invitations#decline", as: "decline_invitation"
  resources :viewers

  get '/search', to: 'searches#index', as: 'search'
  
  resources :activities
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :actualities
    resources :call_for_ideas
    resources :comments
      resources :avatar, only: %i[new create destroy]

    resources :ideas
    patch "/allow_idea/:id", to: "ideas#admin_update", as: "admin_idea"
    get "/share-an-idea", to: "ideas#new"
    post "/share-an-idea", to: "ideas#create"
    resources :options
    resources :questions
    resources :surveys
    post "/surveys/:id", to: "surveys#answer"
    ###### pages #####
    get "/my-space", to: "spaces#index"
    get "/:name/about", to: "spaces#show", as: "about"
    ##################
    get "/my-profile", to: "users#show", as: "my_profile"
    get "/edit-my-profile", to: "users#edit"
    patch "/edit-my-profile", to: "users#update"

    resources :spaces, excpect: %i[new destroy]
    patch "/join_space/:id/:user_id", to: "spaces#join", as: "join_space"
    get "/visit-space", to: "spaces#index", as: "visit_space"
    get "/edit-my-space", to: "spaces#edit"
    patch "/edit-my-space", to: "spaces#update"
    get "/create-a-survey", to: "surveys#new"
    post "/create-a-survey", to: "surveys#create"
    resources :projects
    get "/create-a-project", to: "projects#new"
    post "/create-a-project", to: "projects#create"
    get "/share-an-actuality", to: "actualities#new"
    post "/share-an-actuality", to: "actualities#create"

    root to: "pages#home"
    resources :users, only: %i[index]
    get '/users/show/:id', to: 'users#show',  as: 'user' 
    delete '/kick-out/:id', to: "users#kick_out", as: "kick_out"
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    	sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks",
      passwords: "users/passwords"
    }
  end
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  mount ActionCable.server => "/cable"
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/zarao_controller.rb
class ZaraoController < ApplicationController
end

app/helpers/zarao_helper.rb
module ZaraoHelper
end

app/views/zarao/_css.html.erb
<link rel="icon" type="image/png" href="/assets/logo_zarao.png">
<% if page_need_mdb_pro %>
<%= render 'mdb_pro/css' %>
<% else %>
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<!-- CSS Files -->
<link href="/assets/css/material-kit.css?v=2.0.6" rel="stylesheet" />
<!-- CSS Just for demo purpose, don't include it in your project -->
<link href="/assets/demo/demo.css" rel="stylesheet" />
<% end %>
<link rel="stylesheet" href="/assets/summernote-dist/summernote-bs4.css">
<link rel="stylesheet" type="text/css" href="/assets/linx-css/form.css">
<style type="text/css">
.note-editor.note-frame.card {
    margin: 0 !important;
}
</style>
<%= render 'tails/css' %>
<style type="text/css">
.spinner {
    border-radius: 50%;
    border-top: 4px solid #9c27b0;
    border-left: 4px solid white;
    border-right: 4px solid white;
    border-bottom: 4px solid #9c27b0;
    width: 50px;
    height: 50px;
}
</style>

app/views/zarao/_flash.html.erb
<% if flash.any? %>
<div id="flashes" class="w-xs-100 p-1 w-xs-100 right-0">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> mb-0 zi-1000 w-auto">
        <div class="container">
            <div class="alert-icon">
                <% case key %>
                <% when 'danger' %>
                <i class="material-icons">error_outline</i>
                <% when 'warning' %>
                <i class="material-icons">warning</i>
                <% when 'success' %>
                <i class="material-icons">check</i>
                <% when 'info' %>
                <i class="material-icons">info_outline</i>
                <% end %>
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="material-icons" style="color: brown;">clear</i></span>
            </button>
            <b><%= key.capitalize %> alert:</b><%= value %>
        </div>
    </div>
    <% end %>
</div>
<% end %>

app/views/zarao/_footer.html.erb
<footer class="footer" data-background-color="black">
    <div class="container">
        <div class="row">
            <div class="col-3 col-xs-12">
                <nav class="text-left">
                    <h3 class="mt-2"><a href="<%= user_signed_in? ? '/my-space' : '/' %>" style="color: #9c27b0;">Zarao</a></h3>
                </nav>
            </div>
            <div class="col-9 col-xs-12 text-right">
                <div class="copyright text-right">
                    <%= (t 'footer.copyright').html_safe %>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/zarao/_js.html.erb
<!--   Core JS Files   -->
<!-- <script src="/assets/js/core/jquery.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js/core/popper.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js/plugins/moment.min.js"></script> -->
<!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<!-- <script src="/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script> -->
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<!-- <script src="/assets/js/plugins/nouislider.min.js" type="text/javascript"></script> -->
<!--  Google Maps Plugin    -->
<!-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script> -->
<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
<!-- <script src="/assets/js/material-kit.js?v=2.0.6" type="text/javascript"></script> -->
<%= render 'mdb_pro/js' %>

<script>
/* When the openFullscreen() function is executed, open the video in fullscreen.
Note that we must include prefixes for different browsers, as they don't support the requestFullscreen method yet */
function toggleFullscreen(elem) {
    elem = elem || document.documentElement;
    if (!document.fullscreenElement && !document.mozFullScreenElement &&
        !document.webkitFullscreenElement && !document.msFullscreenElement) {
        if (elem.requestFullscreen) {
            elem.requestFullscreen();
        } else if (elem.msRequestFullscreen) {
            elem.msRequestFullscreen();
        } else if (elem.mozRequestFullScreen) {
            elem.mozRequestFullScreen();
        } else if (elem.webkitRequestFullscreen) {
            elem.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
        }
    } else {
        if (document.exitFullscreen) {
            document.exitFullscreen();
        } else if (document.msExitFullscreen) {
            document.msExitFullscreen();
        } else if (document.mozCancelFullScreen) {
            document.mozCancelFullScreen();
        } else if (document.webkitExitFullscreen) {
            document.webkitExitFullscreen();
        }
    }
}

// jQuery(document).ready(function($) {
//     document.getElementById('questions-list').addEventListener('dblclick', function() {
//         toggleFullscreen(this);
//     });
// });
</script>
<script>
$(document).ready(function() {
    //init DateTimePickers
    materialKit.initFormExtendedDatetimepickers();

    // Sliders Init
    // materialKit.initSliders();
});

function scrollToDownload() {
    if ($('.section-download').length != 0) {
        $("html, body").animate({
            scrollTop: $('.section-download').offset().top
        }, 1000);
    }
}
</script>
<script type="text/javascript" src="/assets/summernote-dist/summernote-bs4.js"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $('.summernote').summernote({
        height: 300,
        tabsize: 2
    });
});
</script>
<!-- <script type="text/javascript">
function bgClickable() {

    $(`.img-clickable`).click(function(event) {
        /* Act on the event */
        event.preventDefault();
        window.location.href = $(this).attr('href');
    });
};
bgClickable();
</script> -->
<% if user_signed_in? %>
<script type="text/javascript">
function updateUserLanguage(language_id = 0) {
    $auth_token = $(`input[name='authenticity_token']`).val(),
        $language_id = language_id;
    $.ajax({
        url: `<%= edit_my_profile_path %>`,
        type: 'PATCH',
        dataType: 'script',
        data: {
            authenticity_token: $auth_token,
            'user[language_id]': $language_id
        }
    });
}
</script>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $(`.language`).click(function(event) {
        $language_id = $(this).attr('data-language-id');
        updateUserLanguage(language_id = $language_id);
    });
});
</script>
<% end %>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $(`.language`).click(function(event) {
        event.preventDefault();
        $current_url = String(`<%= "#{request.fullpath}" %>`);

        $old_language = '<%= "#{request.fullpath.slice(0..2)}" %>';

        $new_language = String($(this).attr('for'));

        if (`${$old_language}` == "/mg" || `${$old_language}` == "/en" || `${$old_language}` == "/fr") {
            $new_url = $current_url.replace(`${$old_language}`, `/${$new_language}`);
        } else {
            $new_url = "/" + $new_language + $current_url;
        }

        setTimeout(function() {
            window.location.href = $new_url;
        }, 500);
    });
});
</script>
<script type="text/javascript">
// function readURL(input) {
//     if (input.files && input.files[0]) {

//         var reader = new FileReader();

//         reader.onload = function(e) {
//             $('.image-upload-wrap').hide();

//             $('.file-upload-image').attr('src', e.target.result);
//             $('.file-upload-content').show();

//             $('.image-title').html(input.files[0].name);
//         };

//         reader.readAsDataURL(input.files[0]);

//     } else {
//         removeUpload();
//     }
// }

// function removeUpload() {
//     $('.file-upload-input').replaceWith($('.file-upload-input').clone());
//     $('.file-upload-content').hide();
//     $('.image-upload-wrap').show();
// }
// $('.image-upload-wrap').bind('dragover', function() {
//     $('.image-upload-wrap').addClass('image-dropping');
// });
// $('.image-upload-wrap').bind('dragleave', function() {
//     $('.image-upload-wrap').removeClass('image-dropping');
// });

function getCallForIdea(project_id = 0) {
    $.ajax({
        url: '/call_for_ideas',
        type: 'GET',
        dataType: 'script',
        data: { project_id: project_id }
    });
}

function getComments(idea_id = 0, project_id = 0) {
    $.ajax({
        url: '/comments',
        type: 'GET',
        dataType: 'script',
        data: { idea_id: idea_id, project_id: project_id }
    });
}

function getOptions(question_id) {
    $.ajax({
        url: '/options',
        type: 'GET',
        dataType: 'script',
        data: { question_id: question_id }
    });
}

function createOption(question_id, name) {
    $auth_token = $(`input[name="authenticity_token"]`).val();
    $.ajax({
        url: '/options',
        type: 'POST',
        dataType: 'script',
        data: {
            authenticity_token: $auth_token,
            'option[question_id]': question_id,
            'option[name]': name
        }
    });
}

function getQuestions() {
    $.ajax({
        url: '/questions',
        type: 'GET',
        dataType: 'script'
    });
}


function editInput() {
    $(`[data-editable="true"]`).keyup(function(event) {
        let id = $(this).attr('id'),
            url = $(this).attr('data-url'),
            content = $(this).val(),
            contentName = $(this).attr('name');
        updateInput(id = id, url = url, content = content, contentName = contentName);
    });
}

editInput();

function updateInput(id = null, url = "", content = "", contentName = "") {
    $locale = $(`html`).attr('lang');
    $auth_token = $(`input[name='authenticity_token']`).val(),
        $id = id, $url = url, $content = content, $contentName = contentName;
    console.log($contentName);
    $attributes = ["authenticity_token", "id", $contentName],
        $values = [$auth_token, $id, $content];
    $data = {
        authenticity_token: $auth_token,
        id: $id,
        "question[name]": $content
    };
    $.ajax({
        url: $url,
        type: 'PATCH',
        dataType: 'script',
        data: $data
    });
}


function getRatings(idea_id = 0, project_id = 0, call_for_idea_id = 0) {
    $.ajax({
        url: '/ratings',
        type: 'GET',
        dataType: 'script',
        data: {
            idea_id: idea_id,
            project_id: project_id,
            call_for_idea_id: call_for_idea_id
        }
    });
}

function rate() {
    $('.rating-label').click(function(event) {
        rating_negative = $(`#rating_negative`);
        event.preventDefault();
        if ($(this).hasClass('positive')) {
            rating_negative.removeAttr('checked');
        } else {
            rating_negative.attr('checked', 'checked');
        }
        setTimeout(function() {
            $(`#submit-rating-btn`).trigger('click');
        }, 100);
    });
};

function unclick() {
    return false;
}

function removeCard() {
    $(`.remove`).click(function(event) {
        /* Act on the event */
        $target = $($(this).attr('for'));
        $modal = $($(this).attr('for') + "-modal");
        $modal.modal('hide');
        $target.fadeOut('slow', function() {
            $target.remove();
        });
    });
}

function getReady() {
    $clickTime = 0;
    $(`#fake-ready-btn`).click(function(event) {
        $clickTime += 1;
        if ($clickTime % 2 != 0) {
            $(`[name*=ready]`).attr('checked', 'checked');
            $(`[name*=confirmed]`).attr('checked', 'checked');
        } else {
            $(`[name*=ready]`).removeAttr('checked');
            $(`[name*=confirmed]`).removeAttr('checked');
        };
    });
}
</script>
<%= render 'tails/js' %>
<script type="text/javascript" src="/assets/linx-js/forms/submit-form.js"></script>
<script type="text/javascript">
$spinner = $(`<section><div class="spinner rotating mx-auto"></div></section>`);
jQuery(document).ready(function($) {
    submitForm(form_tag = 'form.with-loader', loader = $spinner);
});
</script>
<script type="text/javascript" src="/assets/linx-js/inputs/checkbox-submit.js"></script>
<script type="text/javascript" src="/assets/linx-js/flashes/flash.js"></script>
<script type="text/javascript" src="/assets/linx-js/scroll-here.js"></script>
<script type="text/javascript">
    $(document).on('ready turbolinks:load', function() {
        scrollHere(where_id = '.scroll-here');
    });
</script>

app/views/zarao/_navbar.html.erb
<%= render "zarao/flash" %>

app/views/zarao/_offline-nav.html.erb
<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="collapse">
        <%= form_with(url: "/") do |f| %>
        <% end %>
    </div>
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="<%= user_signed_in? ? '/my-space' : '/' %>">
                <img src="/assets/zarao-logo-white.png" width="100"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" style="color: black">
            <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                <li class="nav-item">
                    <a href="<%= search_path(item: 'space', q: '*') %>" class="nav-link text-dark">
                        <i class="material-icons fa fa-wpexplorer"></i>
                        <%= t('navbar.available_spaces') %>
                    </a>
                </li>
                <% else %>
                <li class="nav-item">
                    <a href="<%= visit_space_path %>" class="nav-link text-dark">
                        <i class="material-icons fa fa-wpexplorer"></i>
                        <%= t('spaces.visit') %>
                    </a>
                </li>
                <% end %>
                <li class="dropdown nav-item">
                    <a href="javascript:;" class="dropdown-toggle nav-link text-dark" data-toggle="dropdown">
                        <i class="material-icons">apps</i>
                        <% if user_signed_in? %>
                        <%= @space.name %>
                        <% else %>
                        Menu
                        <% end %>
                    </a>
                    <div class="dropdown-menu dropdown-with-icons">
                        <% if user_signed_in? %>
                        <a href="<%= my_space_path %>" class="dropdown-item">
                            <i class="material-icons fa fa-group"></i>
                            <%= t 'navbar.my_space' %></a>
                        <a href="/my-profile" class="dropdown-item">
                            <i class="material-icons fa fa-user-o"></i>
                            <%= t 'navbar.my_profile' %></a>
                        <a href="<%= edit_user_registration_path %>" class="dropdown-item">
                            <i class="material-icons fa fa-cog"></i>
                            <%= t 'navbar.settings' %></a>
                        <% if current_user.super_admin? %>
                        <a href="/admin" class="dropdown-item">
                            <i class="material-icons fa fa-cogs"></i>
                            Admin space</a>
                        <% end %>
                        <a href="/users/sign_out" data-method="DELETE" class="dropdown-item">
                            <i class="material-icons fa fa-sign-out"></i>
                            <%= t 'navbar.log_out' %></a>
                        <% if current_user.is_admin? %>
                        <hr class="mb-1">
                        <a href="/edit-my-space" class="dropdown-item">
                            <i class="material-icons fa fa-edit"></i>
                            <%= t('tags.my_space') %> </a>
                        <% end %>
                        <% else %>
                        <a href="/users/sign_in" class="dropdown-item">
                            <span class="mdc-fab__icon material-icons text-primary">person</span>
                            <%= t 'navbar.sign_in' %></a>
                        <a href="/users/sign_up" class="dropdown-item">
                            <span class="mdc-fab__icon material-icons text-primary">person_add</span>
                            <%= t 'navbar.sign_up' %></a>
                        <% end %>
                    </div>
                </li>
                <% if user_signed_in? %>
                <li class="dropdown nav-item 12">
                    <a href="javascript:;" class="dropdown-toggle nav-link text-dark" data-toggle="dropdown">
                        <i class="fa fa-globe"></i> <span class="pl-1">
                            <%= current_user.language.code.upcase %></span>
                    </a>
                    <div class="dropdown-menu dropdown-with-icons">
                        <% Language.all.each do |language| %>
                        <a data-language-id="<%= language.id %>" for="<%= language.code %>" href="<%= root_path(locale: language.code) %>" class="language dropdown-item">
                            <img src="/assets/flags/<%= language.code %>.png" width="25"> <span class="pl-2">
                                <%= language.name %></span></a>
                        <% end %>
                    </div>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/zarao/_online-nav.html.erb
<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/">
                <img src="/assets/zarao-logo-white.png" width="100">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" style="color: black" >
            <ul class="navbar-nav ml-auto">
              <% if current_user.is_admin? %>
              <li class="nav-item">
                  <a href="<%= edit_my_space_path %>" class="btn btn-link">
                          <i class="material-icons fa fa-user-secret"></i>  Edit my space</a>
              </li>
              <% end %>
              <li class="nav-item">
                  <a href="<%= my_space_path %>" class="btn btn-link">
                          <i class="material-icons fa fa-group"></i> My space</a>
              </li>
                <li class="dropdown nav-item h-xs-12">
                    <li class="dropdown nav-item">
                        <a href="javascript:;" class="profile-photo dropdown-toggle nav-link" data-toggle="dropdown">
                            <div class="row">
                                <% if current_user.has_fullname? %>
                                    <div class="col-8 pr-0 text-center">
                                        <span class="btn btn-link" style="margin-right: -8px!important;"><%= current_user.fullname %></span>
                                    </div>
                                <% end %>
                                <div class="col-2 text-left pl-0 ml-0">
                                    <div class="profile-photo-small">
                                        <%= image_tag current_user.avatar, class: "rounded-circle ", alt: "Circle Image", width: "40",height: "40" %>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-with-icons">
                            <a href="<%= my_profile_path %>" class="dropdown-item">
                                <i class="material-icons fa fa-user"></i> Me</a>
                            <a href="<%= edit_my_profile_path %>" class="dropdown-item">
                                <i class="material-icons fa fa-cogs"></i> Edit profile</a>
                            <a href="<%= edit_user_registration_path %>" class="dropdown-item">
                                <i class="material-icons fa fa-cog"></i> Account setting</a>
                            <a href="/users/sign_out" data-method="DELETE" class="dropdown-item">
                                <i class="material-icons fa fa-sign-out"></i> Sign out</a>
                        </div>
                    </li>

                <!-- <li class="nav-item">
                    <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank" data-original-title="Follow us on Twitter">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank" data-original-title="Like us on Facebook">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial" target="_blank" data-original-title="Follow us on Instagram">
                        <i class="fa fa-instagram"></i>
                    </a>
                </li> -->
            </ul>
        </div>
    </div>
</nav>