config/routes.rb
Rails.application.routes.draw do
  post '/votes/:vote_type/:item_type/:item_id/:short', to: "votes#create", as: "votes"
  delete '/votes/:vote_type/:item_type/:item_id/:short', to: "votes#destroy", as: "vote"
  
  resources :invitations
  get "/accept-invitation/:id/:password_token", to: "invitations#accept", as: "accept_invitation"
  get "/decline-invitation/:id/:password_token", to: "invitations#decline", as: "decline_invitation"
  resources :viewers

  get '/search', to: 'searches#index', as: 'search'
  
  resources :activities
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :actualities
    resources :call_for_ideas
    resources :comments
      resources :avatar, only: %i[new create destroy]

    resources :ideas
    patch "/allow_idea/:id", to: "ideas#admin_update", as: "admin_idea"
    get "/share-an-idea", to: "ideas#new"
    post "/share-an-idea", to: "ideas#create"
    resources :options
    resources :questions
    resources :surveys
    post "/surveys/:id", to: "surveys#answer"
    ###### pages #####
    get "/my-space", to: "spaces#index"
    get "/:name/about", to: "spaces#show", as: "about"
    ##################
    get "/my-profile", to: "users#show", as: "my_profile"
    get "/edit-my-profile", to: "users#edit"
    patch "/edit-my-profile", to: "users#update"

    resources :spaces, excpect: %i[new destroy]
    patch "/join_space/:id/:user_id", to: "spaces#join", as: "join_space"
    get "/visit-space", to: "spaces#index", as: "visit_space"
    get "/edit-my-space", to: "spaces#edit"
    patch "/edit-my-space", to: "spaces#update"
    get "/create-a-survey", to: "surveys#new"
    post "/create-a-survey", to: "surveys#create"
    resources :projects
    get "/create-a-project", to: "projects#new"
    post "/create-a-project", to: "projects#create"
    get "/share-an-actuality", to: "actualities#new"
    post "/share-an-actuality", to: "actualities#create"

    root to: "pages#home"
    resources :users, only: %i[index]
    get '/users/show/:id', to: 'users#show',  as: 'user' 
    delete '/kick-out/:id', to: "users#kick_out", as: "kick_out"
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    	sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks",
      passwords: "users/passwords"
    }
  end
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  mount ActionCable.server => "/cable"
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	after_create :add_cover_picture
  belongs_to :admin, class_name: "User"
  belongs_to :space
  belongs_to :type
  has_many :call_for_ideas
  has_many :users, through: :call_for_ideas
  has_many :ideas, through: :call_for_ideas

  has_many :ratings

  has_one_attached :cover_picture

  def add_cover_picture
  	if !self.cover_picture.attached?
      self.cover_picture.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default-cover-picture.png')), filename: 'default-cover-picture.png', content_type: 'image/png')
  	end
  end

  acts_as_votable
  scope :search_import, -> { includes(:type) }

  def search_data
    {
      types: "#{name} #{type.name}"
    }
  end
  
  # searchkick
  acts_as_commentable
end

app/controllers/projects_controller.rb
class ProjectsController < SpacesController
  
  include ProjectsHelper
  include ApplicationHelper

  before_action :authenticate_user
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_project, only: [:show, :edit]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.safe_all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @call_for_ideas = @project.call_for_ideas
    unless current_user.viewed(@project)
      add_viewer(user_id=current_user.id, project_id=@project.id, idea_id=0, survey_id=0, call_for_idea_id=0, actuality_id=0)
    end
  end

  # GET /projects/new
  def new
    @project = current_space.projects.new
  end

  # GET /projects/1/edit
  def edit
    @call_for_ideas = @project.call_for_ideas
  end

  # POST /projects
  # POST /projects.json
  def create
    deadline = params[:project][:deadline]
    @project = current_space.projects.new(project_params)
    @project.deadline = customized_date
    @project.admin = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_project_path(id: @project.id), info: t('projects.create') }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { redirect_to create_a_project_path, danger: @project.errors.full_messages }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(id: @project.id), success: t('projects.update') }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { redirect_to edit_project_path(id: @project.id), danger: @porject.errors.full_messages }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, success: t('projects.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :type_id, :ready, :cover_picture)
    end

    def authenticate_user
      authenticate_user!
      if action_name=="edit"
        @project = set_project
        unless current_user.is_admin?
          redirect_to "/404.html"
        end
      end
      if action_name != "new" && action_name != "create"
        @project = set_project
      end
    end

    def authenticate_project
      if action_name=="show" && !@project.ready?
        redirect_to edit_project_path(id: @project.id),
        warning: t('projects.warning')
      end
      # if action_name=="edit" && @project.ready?
      #   redirect_to project_path(id: @project.id),
      #   warning: t('projects.editable')
      # end
    end

    def customized_date
      deadline = params[:project][:deadline]
      day = deadline.split("/")[1]
      month = deadline.split("/")[0]
      year = (deadline.split("/")[2]).split(' ')[0]
      time = (deadline.split("/")[2]).split(' ')[1]
      am_or_pm = (deadline.split("/")[2]).split(' ')[2]
      final_date = day+'th'+" "+month+" "+year+" "+time+" "+am_or_pm
      final_date
      final_date.to_datetime
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	# Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :description, :type_id, :ready, :cover_picture)
  end

  def authenticate_project
    if action_name=="show" && !@project.ready?
      redirect_to edit_project_path(id: @project.id),
      warning: t('projects.warning')
    end
    if action_name=="edit" && @project.ready?
      redirect_to project_path(id: @project.id),
      warning: "This project is neiver editable"
    end
  end

  def customized_date
    deadline = params[:project][:deadline]
    day = deadline.split("/")[1]
    month = deadline.split("/")[0]
    year = (deadline.split("/")[2]).split(' ')[0]
    time = (deadline.split("/")[2]).split(' ')[1]
    am_or_pm = (deadline.split("/")[2]).split(' ')[2]
    final_date = day+'th'+" "+month+" "+year+" "+time+" "+am_or_pm
    final_date
    final_date.to_datetime
  end
  
	def authenticate_user
    authenticate_user!
    if action_name=="edit"
      @project = set_project
      unless @project.user == current_user
        redirect_to "/404.html"
      end
    end
    if action_name != "new" && action_name != "create"
      @project = set_project
    end
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, url: project.persisted? ? project_path(id: project.id) : projects_path, data: { remote: false }, html: {id: "create-project-form"}) do |form| %>
<% if action_name=="edit" %>
<%= form.label :name, t('activerecord.attributes.title'), class: "label-floating" %>
<div class="input-group control-group">
    <%= form.text_field :name, class: "form-control", placeholder: "Give a title to your project", required: "" %>
    <div class="input-group-btn collapse">
        <div class="form-check">
            <label class="form-check-label">
                <%= form.check_box :ready, class: "form-check-input" %>
                <%= t('tags.labels.ready') %>
                <span class="form-check-sign">
                    <span class="check"></span>
                </span>
            </label>
        </div>
    </div>
</div>
<% else %>
<div class="form-group">
    <%= form.label :name, t('activerecord.attributes.title'), class: "label-floating" %>
    <%= form.text_field :name, class: "form-control", placeholder: t('projects.name') , required: "" %>
</div>
<% end %>
<% if action_name=="edit" %>
<div class="md-form form-group">
    <%= form.label :deadline, t('activerecord.attributes.end_date') %>
    <div class="row">
        <div class="col">
            <%= form.datetime_field :deadline, class: "form-control" %>
        </div>
        <div class="col">
            <input type="text" value="<%= I18n.l(project.deadline, format: :long) %>" name="" autocomplete="" readonly="readonly" class="form-control">
        </div>
    </div>
</div>
<% else %>
<div class="form-group">
    <%= form.label :deadline, class: "label-control" %>
    <%= form.text_field :deadline, class: "form-control datetimepicker", required: "" %>
</div>
<% end %>
<div class="form-group">
    <%= form.label :cover_picture, t('tags.labels.cover_picture') %>
    <div class="file-upload">
        <div class="file-upload-content">
            <img class="file-upload-image w-100 img-thumbnail br-0" src="<%= project.cover_picture.attached? ? url_for(project.cover_picture) : " javascript:;" %>" alt="your image" />
            <div class="image-title-wrap text-left">
                <button type="button" onclick="removeUpload()" class="remove-image btn btn-danger pt-3 w-auto">Remove <span class="image-title">Uploaded Image</span></button>
            </div>
        </div>
        <div class="image-upload-wrap">
            <%= form.file_field :cover_picture, accept: ".png, .jpg, .jpeg", class: "file-upload-input", onchange: "readURL(this);" %>
            <label class="drag-text" for="project_cover_picture" style="display: block; cursor: pointer;">
                <h3>
                    <%= t('tags.labels.drag_and_drop_a_file') %>
                </h3>
            </label>
        </div>
    </div>
</div>
<div class="form-group">
    <%= form.label :type, t('activerecord.attributes.type'), class: "bmd-label-floating" %>
    <select name="project[type_id]" id="project_type_id" class="form-control">
        <% if project.persisted? %>
        <option value="<%= project.type.id %>">
            <%= t("types.#{project.type.id}") %>
        </option>
        <% end %>
        <% Type.all.each do |type| %>
        <% next if type == project.type %>
        <option value="<%= type.id %>">
            <%= t("types.#{type.id}") %>
        </option>
        <% end %>
    </select>

</div>
<div class="form-group">
    <%= form.label :description, class: "label-control mb-0" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Okay guys this is certainly the best project that you've never heard so listen to me carefully ...\nyou can add some images, videos and files ...", required: "" %>
</div>
<div class="actions">
    <%= form.submit "Save", class: "btn btn-md collapse", id: "save-project-btn" %>
</div>
<% end %>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $(`#fake-btn`).click(function(event) {
        event.preventDefault();
        $(`#save-project-btn`).click();
    });
});
</script>

app/views/projects/_index.html.erb
<% if projects.any?  %>
<% projects.each do |project|  %>
<%= render 'shared/show_item', item: project, classes: "col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 p-xs-0" %>
<% end %>
<% else %>
<%= t('spaces.no_available_project') %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'shared/nota-bene' %>
<div class="row makeTop scroll-here" scroll-to="50">
    <div class="col-12 offset-0">
        <div class="card pb-2 pt-1">
            <div class="container mt-7">
                <div class="row">
                    <div class="col-12 offset-0">
                        <div class="">
                            <!-- Card header -->
                            <div class="card-header text-center">
                                <%= t('projects.check_your_project') %>
                            </div>
                            <!--Card content-->
                            <div class="card-body">
                                <div id="accordion" role="tablist">
                                    <div class="card card-collapse">
                                        <div class="" role="tab" id="project-form">
                                            <h5 class="m-0 px-2">
                                                <a data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="collapsed" style="color: rgb(156, 39, 176);">
                                                    <%= t('projects.edit') %>
                                                    <i class="material-icons">keyboard_arrow_down</i>
                                                </a>
                                            </h5>
                                        </div>
                                        <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="project-form" data-parent="#accordion" style="">
                                            <div class="card-body">
                                                <%= render 'projects/form', project: @project %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card card-collapse mt-3">
                                        <div class="" role="tab" id="call-for-idea-form">
                                            <h5 class="m-0 px-2">
                                                <a class="" data-toggle="collapse" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo" style="color: rgb(156, 39, 176);">
                                                    <%= t('projects.add') %>
                                                    <i class="material-icons">keyboard_arrow_down</i>
                                                </a>
                                            </h5>
                                        </div>
                                        <div id="collapseTwo" class="collapse show" role="tabpanel" aria-labelledby="call-for-idea-form" data-parent="#accordion" style="">
                                            <div class="card-body">
                                                <script type="text/javascript">
                                                getCallForIdea(<%= @project.id %>);
                                                </script>
                                                <%= render 'call_for_ideas/new', project: @project, call_for_idea: CallForIdea.new %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card card-collapse mt-3">
                                        <div class="" role="tab" id="call-for-idea-form">
                                            <h5 class="m-0 px-2">
                                                <a class="" data-toggle="collapse" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree" style="color: rgb(156, 39, 176);">
                                                    <%= t('call_for_idea.title') %>
                                                    <i class="material-icons">keyboard_arrow_down</i>
                                                </a>
                                            </h5>
                                        </div>
                                        <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="call-for-idea-form" data-parent="#accordion" style="">
                                            <section id="call_for_ideas">
                                            </section>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group-btn">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="checkbox" name="" id="fake-ready-btn" checked="<%= @project.ready? ? true : false %>" class="form-check-input">
                                                <%= t('tags.labels.ready') %>
                                                <span class="form-check-sign">
                                                    <span class="check"></span>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                    <button id="fake-btn" class="btn btn-md">
                                        <%= t('tags.buttons.save_changes') %></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'shared/tinymce-editor', textarea: "textarea#project_description", menubar: "file insert" %>
<script type="text/javascript">
$('.file-upload-content').show();
$('.image-upload-wrap').hide();
getReady();
</script>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Ready</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.admin_id %></td>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.type_id %></td>
        <td><%= project.ready %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<%= render 'shared/nota-bene' %>
<div class="row makeTop scroll-here" scroll-to="50">
    <div class="col-12 offset-0">
        <div class="card pb-2 pt-1">
            <div class="container">
                <div class="row">
                    <div class="col-12 offset-0">
                        <h4>
                            <%= t('projects.new') %>
                        </h4>
                        <%= render 'projects/form', project: @project %>
                        <button id="fake-btn" class="btn btn-md float-right">
                            <%= t('tags.buttons.save') %> </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'shared/tinymce-editor', textarea: "textarea#project_description", menubar: "file insert" %>

app/views/projects/show.html.erb
<!--Section: Post-->
<div class="mt-3">
    <div class="card mb-4">
        <!--Card content-->
        <div class="ImgBoxes m-0 br-0 br-t-5" <% if @project.cover_picture.image? %> style="background: url(
            <%= url_for(@project.cover_picture) %>) no-repeat black center"
            <% end %>>
            <% if @project.cover_picture.image? %>
            <% elsif @project.cover_picture.video? %>
            <video style="width: 100%; height: 100%;" controls="" autoplay="autoplay">
                <source src="<%= url_for(@project.cover_picture) %>" type="">
                Video not supported
            </video>
            <% else %>
            File not supported
            <% end %>
        </div>
        <% if current_user == @project.admin %>
        <%= link_to [:edit, @project, locale: I18n.locale], data: {turbolinks: false}, class: "text-primary close zi-1 ml-auto" do %>
        <i class="fa fa-edit fa-2x"></i>
        <% end %>
        <% end %>
        <div class="card-body pt-5">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <%= t('tags.by') %> <a href="<%= user_path(id: @project.admin.id) %>" style="color: rgb(156, 39, 176);">
                                <%= @project.admin.fullname %> </a>
                            <%= t('tags.one') %>
                            <%= I18n.l(@project.created_at, format: :short) %>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div class="text-right">
                                <span class="badge badge-info"><i class="fa fa-eye"></i>
                                    <%= count(@project.viewers.length) %></span> |
                                <span class="badge badge-info"><i class="fa fa-lightbulb-o"></i>
                                    <%= count(@project.ready_ideas.length) %></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <p class="h2 my-4">
                <%= @project.name %>
            </p>
            <p class="h5 my-4">
                <%= @project.type.name   %>
            </p>
            <div class="row">
                <div class="col-sm-11">
                    <p>
                        <%= @project.html_description %>
                    </p>
                </div>
                <div class="col-sm-1">
                    <section id="ratings-idea-<%= @project.id %>" class="ratings"></section>
                    <dl>
                        <dd id="project-<%= @project.id %>-positive_report">
                            <%= render 'votes/report', vote_type: "positive_report", item: @project, item_type: "project", vote_weight: 1, color: "success" %>
                        </dd>
                        <dd id="project-<%= @project.id %>-negative_report">
                            <%= render 'votes/report', vote_type: "negative_report", item: @project, item_type: "project", vote_weight: 1, color: "danger" %>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
<% if @call_for_ideas.any? %>
<div class="">
    <div class="card-header-pills" role="tab" id="call-for-ideas">
        <h5 class="m-0 px-2">
            <a class="" data-toggle="collapse" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo" style="color: rgb(156, 39, 176);">
                <%= t('call_for_idea.length', count: @call_for_ideas.length) %>
                <i class="material-icons">keyboard_arrow_down</i>
            </a>
        </h5>
    </div>
    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="call-for-ideas" data-parent="#accordion" style="">
        <div class="p-0 w-100">
            <div class="card-header text-center">
                <h4 class="card-title rounded">
                    <%= t('call_for_idea.title') %>
                </h4>
            </div>
            <div class="row">
                <% @call_for_ideas.each do |call_for_idea| %>
                <div class="col-md-4">
                    <div class="card card-blog">
                        <div class="card-header card-header-image">
                            <a href="<%= call_for_idea_path(id: call_for_idea.id) %>" class="rounded" style="max-height: 300px; overflow-y: hidden;">
                                <img src="<%= url_for(call_for_idea.cover_picture) %>" alt="">
                            </a>
                        </div>
                        <div class="card-body">
                            <h6 class="card-category text-warning">
                                <%= call_for_idea.name %>
                            </h6>
                            <h4 class="card-title">
                                <a href="#pablo">
                                    <%= call_for_idea.description %></a>
                            </h4>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<% end %>
<section class="my-5">
    <div class="card-body p-0">
        <%= render 'comments/new', comment: Comment.build_from( @project, current_user.id, '' ), item: @project, item_id: @project.id, item_type: 'project' %>
        <section id="project-<%= @project.id %>-comments" class="comments">
            <%= render 'comments/index', comments: @project.comments, defcon: 0 %>
        </section>
    </div>
</section>