config/routes.rb
Rails.application.routes.draw do
  post '/votes/:vote_type/:item_type/:item_id/:short', to: "votes#create", as: "votes"
  delete '/votes/:vote_type/:item_type/:item_id/:short', to: "votes#destroy", as: "vote"
  
  resources :invitations
  get "/accept-invitation/:id/:password_token", to: "invitations#accept", as: "accept_invitation"
  get "/decline-invitation/:id/:password_token", to: "invitations#decline", as: "decline_invitation"
  resources :viewers

  get '/search', to: 'searches#index', as: 'search'
  
  resources :activities
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :actualities
    resources :call_for_ideas
    resources :comments
      resources :avatar, only: %i[new create destroy]

    resources :ideas
    patch "/allow_idea/:id", to: "ideas#admin_update", as: "admin_idea"
    get "/share-an-idea", to: "ideas#new"
    post "/share-an-idea", to: "ideas#create"
    resources :options
    resources :questions
    resources :surveys
    post "/surveys/:id", to: "surveys#answer"
    ###### pages #####
    get "/my-space", to: "spaces#index"
    get "/:name/about", to: "spaces#show", as: "about"
    ##################
    get "/my-profile", to: "users#show", as: "my_profile"
    get "/edit-my-profile", to: "users#edit"
    patch "/edit-my-profile", to: "users#update"

    resources :spaces, excpect: %i[new destroy]
    patch "/join_space/:id/:user_id", to: "spaces#join", as: "join_space"
    get "/visit-space", to: "spaces#index", as: "visit_space"
    get "/edit-my-space", to: "spaces#edit"
    patch "/edit-my-space", to: "spaces#update"
    get "/create-a-survey", to: "surveys#new"
    post "/create-a-survey", to: "surveys#create"
    resources :projects
    get "/create-a-project", to: "projects#new"
    post "/create-a-project", to: "projects#create"
    get "/share-an-actuality", to: "actualities#new"
    post "/share-an-actuality", to: "actualities#create"

    root to: "pages#home"
    resources :users, only: %i[index]
    get '/users/show/:id', to: 'users#show',  as: 'user' 
    delete '/kick-out/:id', to: "users#kick_out", as: "kick_out"
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    	sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks",
      passwords: "users/passwords"
    }
  end
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  mount ActionCable.server => "/cable"
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
  after_create :add_cover_picture
  belongs_to :admin, class_name: "User"
  belongs_to :space
  has_many :questions, dependent: :destroy
  has_many :options, through: :questions
  has_many :users, through: :questions
  validates_presence_of :name, :end_date, :description

  belongs_to :type
  has_one_attached :cover_picture

  def finished?
  	self.end_date.past?
  end

  def ready?
  	self.questions.any? && self.ready
  end

  def add_cover_picture
    if !self.cover_picture.attached?
      self.cover_picture.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default-cover-picture.png')), filename: 'default-cover-picture.png', content_type: 'image/png')
    end
  end

  def safe_users
    users = []
    self.users.each do |user|
      users << user if !users.include?(user)
    end
    return users
  end

  scope :search_import, -> { includes(:type) }

  def search_data
    {
      types: "#{name} #{type.name}"
    }
  end

  # searchkick
  acts_as_votable
  acts_as_commentable

  def comments
    self.comment_threads
  end
end

app/controllers/surveys_controller.rb
class SurveysController < SpacesController  
  before_action :authenticate_user!
  before_action :authenticate_admin, only: %i[edit update new create destroy]
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_survey, only: [:show, :edit]

  include ApplicationHelper
  include SpacesHelper
  include SurveysHelper
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.safe_all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    unless current_user.viewed(@survey)
      add_viewer(user_id=current_user.id, project_id=0, idea_id=0, survey_id=@survey.id, call_for_idea_id=0, actuality_id=0)
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    end_date = params[:survey][:end_date]
    @survey = current_space.surveys.new(survey_params)
    @survey.end_date = customized_date
    @survey.admin = current_user

    respond_to do |format|
      if @survey.save
        format.html { redirect_to edit_survey_path(id: @survey.id), info: t('surveys.add') }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { redirect_to create_a_survey_path, danger: @survey.errors.full_messages }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(update_survey_params)
        format.html { redirect_to survey_path(id: @survey.id), success: t('surveys.update') }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { redirect_to edit_survey_path(id: @survey.id), danger: @survey.errors.full_messages }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, success: t('surveys.destroy') }
      format.json { head :no_content }
    end
  end

  def answer
    @survey = set_survey
    options = []
    params.require(:question).each do |key, value|
      options << Option.find(value)
    end
    if params[:option]
      params.require(:option).each do |key, value|
        options << Option.find(value)
      end
    end
    options.each do |option|
      option.users.push(current_user)
    end
    respond_to do |format|
      if options.any?
        format.html { redirect_to survey_path(id: @survey.id), success: t('surveys.success') }
        format.js
      else
        format.html { redirect_to survey_path(id: @survey.id), danger: "Unknown error" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = current_survey
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:type_id, :name, :description, :end_date, :cover_picture)
    end

    def update_survey_params
      params.require(:survey).permit(:type_id, :name, :description, :ready, :cover_picture)
    end

    def authenticate_admin
      unless (current_user.admin? && current_space == current_user.main_space) || current_user.super_admin?
        redirect_to '/404.html'
      end
    end

    def authenticate_survey
      if action_name=="show" && !@survey.ready?
        redirect_to edit_survey_path(id: @survey.id),
        warning: t('surveys.warning')
      end
      if action_name=="edit" && @survey.ready?
        redirect_to survey_path(id: @survey.id),
        warning: t('surveys.editable')
      end
    end

    def customized_date
      end_date = params[:survey][:end_date]
      day = end_date.split("/")[1]
      month = end_date.split("/")[0]
      year = (end_date.split("/")[2]).split(' ')[0]
      time = (end_date.split("/")[2]).split(' ')[1]
      am_or_pm = (end_date.split("/")[2]).split(' ')[2]
      final_date = day+'th'+" "+month+" "+year+" "+time+" "+am_or_pm
      final_date
      final_date.to_datetime
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
	def current_survey
		if session[:survey_id] != params[:id]
			session[:survey_id] = params[:id]
		end

		Survey.find(session[:survey_id])
	end

	def you_are_in_this(survey)
		survey.questions.each do |question|
			question.options.each do |option|
				return true if option.users.include?(current_user)
			end
		end
		return false
	end
end

app/views/surveys/_form.html.erb
<div class="container mt-6">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-10 col-lg-10 col-xl-10 offset-md-1 offset-lg-1 offset-xl-1">
            <h1>
                <%= t('surveys.update_survey') %>
            </h1>
            <%= form_with(model: survey, url: survey_path(id: survey.id), local: true, html: {id: "update-survey-form", class: "scroll-here", 'scroll-to': '50'}) do |form| %>
            <%= render 'shared/error_messages', item: survey %>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="form-group">
                        <%= form.label :name, t('activerecord.attributes.title'), class: "bmd-label-floating", required: "" %>
                        <%= form.text_field :name, class: "form-control", required: "", required: "" %>
                        <div class="input-group-btn collapse">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <%= form.check_box :ready, class: "form-check-input" %>
                                    <%= t('tags.labels.ready') %>
                                    <span class="form-check-sign">
                                        <span class="check"></span>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <% if action_name=="edit" %>
            <div class="md-form form-group">
                <%= form.label :end_date, t('activerecord.attributes.end_date'), required: "" %>
                <div class="row">
                    <div class="col">
                        <%= form.datetime_field :end_date, class: "form-control", required: "" %>
                    </div>
                    <div class="col">
                        <input type="text" value="<%= I18n.l(survey.end_date, format: :long) %>" name="" autocomplete="" readonly="readonly" class="form-control">
                    </div>
                </div>
            </div>
            <% else %>
            <div class="form-group">
                <%= form.label :end_date, t('activerecord.attributes.end_date'), class: "label-control", required: "" %>
                <%= form.text_field :end_date, class: "form-control datetimepicker", required: "", required: "" %>
            </div>
            <% end %>
            <div class="form-group">
                <%= form.label :type, t('activerecord.attributes.type'), class: "bmd-label-floating", required: "" %>
                <select name="survey[type_id]" id="survey_type_id" class="form-control">
                    <option value="<%= survey.type.id %>">
                        <%= t("types.#{survey.type.id}") %>
                    </option>
                    <% Type.all.each do |type| %>
                    <% next if type == survey.type %>
                    <option value="<%= type.id %>">
                        <%= t("types.#{type.id}") %>
                    </option>
                    <% end %>
                </select>
            </div>
            <div class="form-group">
                <%= form.label :cover_picture, t('tags.labels.cover_picture'), required: "" %>
                <div class="file-upload">
                    <div class="file-upload-content">
                        <img class="file-upload-image w-100 img-thumbnail br-0" src="<%= survey.cover_picture.attached? ? url_for(survey.cover_picture) : " javascript:;" %>" alt="your image" />
                        <div class="image-title-wrap text-left">
                            <button type="button" onclick="removeUpload()" class="remove-image btn btn-danger pt-3">Remove <span class="image-title">Uploaded Image</span></button>
                        </div>
                    </div>
                    <div class="image-upload-wrap">
                        <%= form.file_field :cover_picture, class: "file-upload-input", onchange: "readURL(this);", required: "" %>
                        <label class="drag-text" for="survey_cover_picture" style="display: block; cursor: pointer;">
                            <h3>
                                <%= t('tags.labels.drag_and_drop_a_file') %>
                            </h3>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="label-control mb-0">
                    <%= t('activerecord.attributes.description') %></label>
                <div class="summernote">
                    <p>
                        <%= survey.html_description %>
                    </p>
                </div>
                <div class="collapse">
                    <%= form.text_area :description, class: "form-control", required: "", required: "" %>
                </div>
            </div>
            <div class="form-check collapse">
                <label class="form-check-label">
                    <%= form.check_box :confirmed, class: "form-check-input" %>
                    <%= t('tags.labels.ready') %>
                    <span class="form-check-sign">
                        <span class="check"></span>
                    </span>
                </label>
            </div>
            <div class="actions">
                <button type="button" class="btn" data-toggle="popover" data-placement="left" title="Need help ?" data-content="When you have successfully add at least one question and some options to your survey, you can check the 'Ready checkbox' then you submit changes and your survey is published." data-container="body"><i class="fa fa-question-circle-o"></i></button>
            </div>
            <button class="btn btn-block" id="">
                <%= t('tags.buttons.save_changes') %></button>
            <% end %>
        </div>
    </div>
</div>
<style type="text/css">
.note-editor.note-frame.card {
    margin-top: 0;
}
</style>
<% if action_name=="edit" %>
<script type="text/javascript">
$('.file-upload-content').show();
$('.image-upload-wrap').hide();
</script>
<% end %>
<script type="text/javascript">
$(document).on('ready turbolinks:load', function() {
    $(`#fake-update-btn`).click(function(event) {
        event.preventDefault();
        $(`#update-survey-form`).submit();
    });
});
</script>
<%= render 'shared/tinymce-editor', textarea: "textarea#survey_description", menubar: "file insert" %>

app/views/surveys/_index.html.erb
<% if surveys.any? %>
<% surveys.each do |survey|  %>
<%= render 'shared/show_item', item: survey, classes: "col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 p-xs-0" %>
<% end %>
<% else %>
<%= t('spaces.no_available_survey') %>
<% end %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.admin_id %></td>
        <td><%= survey.name %></td>
        <td><%= survey.end_date %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/surveys/new.html.erb
<%= render 'shared/nota-bene' %>
<div class="makeTop scroll-here" scroll-to="50">
    <div class="row">
        <div class="col-sm-12">
            <div class="card pb-2 pt-1">
                <div class="container">
                    <div class="">
                        <h4>
                            <%= t('surveys.create_new_survey') %>
                        </h4>
                        <%= form_with(model: @survey, url: surveys_path, local: true, html: {id: "create-survey-form"}) do |form| %>
                        <%= render 'shared/error_messages', item: @survey %>
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8">
                                <div class="form-group">
                                    <%= form.label :name, t('activerecord.attributes.title'), class: "bmd-label-floating" %>
                                    <%= form.text_field :name, class: "form-control", required: "" %>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <%= form.label :end_date, t('activerecord.attributes.end_date'), class: "label-control" %>
                                    <%= form.text_field :end_date, class: "form-control datetimepicker", required: "" %>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <%= form.label :type, t('activerecord.attributes.type'), class: "bmd-label-floating" %>
                            <select name="survey[type_id]" id="survey_type_id" class="form-control">
                                <% Type.all.each do |type| %>
                                <option value="<%= type.id %>">
                                    <%= t("types.#{type.id}") %>
                                </option>
                                <% end %>
                            </select>
                        </div>
                        <div class="form-group">
                            <%= form.label :cover_picture, t('tags.labels.cover_picture') %>
                            <div class="file-upload">
                                <div class="file-upload-content">
                                    <img class="file-upload-image w-100 img-thumbnail br-0" src="<%= @survey.cover_picture.attached? ? url_for(survey.cover_picture) : " javascript:;" %>" alt="your image" />
                                    <div class="image-title-wrap text-left">
                                        <button type="button" onclick="removeUpload()" class="remove-image btn btn-danger pt-3 w-auto">Remove <span class="image-title">Uploaded Image</span></button>
                                    </div>
                                </div>
                                <div class="image-upload-wrap">
                                    <%= form.file_field :cover_picture, class: "file-upload-input", onchange: "readURL(this);" %>
                                    <label class="drag-text" for="survey_cover_picture" style="display: block; cursor: pointer;">
                                        <h3>
                                            <%= t('tags.labels.drag_and_drop_a_file') %>
                                        </h3>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="survey_description" class="label-control mb-0">Description</label>
                            <%= form.text_area :description, class: "form-control", required: "" %>
                        </div>
                        <div class="actions">
                            <%= form.submit t('tags.buttons.save'), id: "create-survey-btn", class: "collapse btn btn-block" %>
                            <%= form.submit t('tags.buttons.save'), id: "fake-create-survey-btn", class: "btn btn-block" %>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).on('ready turbolinks:load', function() {
    $(`#fake-create-survey-btn`).click(function(event) {
        event.preventDefault();
        $(`#create-survey-btn`).click();
    });
});
</script>
<%= render 'shared/tinymce-editor', textarea: "textarea#survey_description", menubar: "file insert" %>

app/views/surveys/show.html.erb
<link href="/assets/mdb-pro-css/msteppers.css" rel="stylesheet">
<script type="text/javascript" src="/assets/mdb-pro-js/msteppers.js"></script>
<!--Section: Post-->
<section class="mt-3">
    <div class="container">
        <div class="row wow fadeIn">
            <div class="col-md-12 px-0">
                <div class="card">
                    <% if current_user == @survey.admin %>
                    <%= link_to [:edit, @survey, locale: I18n.locale], data: {turbolinks: false}, class: "text-primary close zi-1 ml-auto" do %>
                    <i class="fa fa-edit fa-2x"></i>
                    <% end %>
                    <% end %>
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <div class="row">
                                    <div class="col-sm-12 col-md-6">
                                        <%= t('tags.by') %> <a href="<%= user_path(id: @survey.admin.id) %>" style="color: rgb(156, 39, 176);">
                                            <%= @survey.admin.fullname %> </a>
                                        <%= t('tags.one') %>
                                        <%= I18n.l(@survey.created_at, format: :short) %>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <div class="text-right">
                                            <span class="badge badge-info"><i class="fa fa-eye"></i>
                                                <%= count(@survey.viewers.length) %></span> |
                                            <span class="badge badge-info"><i class="fa fa-users"></i>
                                                <%= count(@survey.safe_users.length) %></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <h3>
                                    <%= @survey.name %>
                                </h3>
                            </div>
                        </div>
                        <blockquote class="blockquote bg-dark-o-10">
                            <p>
                                <%= @survey.html_description %>
                            </p>
                            <div class="blockquote-footer">
                                <%= t('activerecord.attributes.deadline') %> :
                                <%= I18n.l(@survey.end_date, format: :long) %>
                            </div>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.Vertical Steppers -->
<% if @survey.finished? %>
<%= render 'surveys/result', survey: @survey, males: @survey.users.where(gender: "male"), females: @survey.users.where(gender: "female") %>
<% elsif you_are_in_this(@survey) %>
<section class="container">
    <div class="jumbotron text-center">
        <strong class="">
            <%= t('surveys.survey_submitted') %></strong>
    </div>
</section>
<% else %>
<div class="container">
    <div class="card px-4">
        <div class="card-content">
            <%= form_with(url: survey_path, data: { remote: false }) do |f| %>
            <ul class="stepper demos list-unstyled">
                <% @survey.questions.each_with_index do |question, id| %>
                <li class="step <% if id == 0 %>active<% end %>">
                    <div data-step-label="<% if id==0 %>
                        <%= t('surveys.labels.question.one', number: id + 1) %>
                        <% else %>
                        <%= t('surveys.labels.question.other', number: id + 1) %>
                        <% end %>" class="step-title  waves-dark">
                        <%= question.name %>
                    </div>
                    <div class="step-content" style="">
                        <div class="row">
                            <% question.options.each_with_index do |option, opt_id| %>
                            <div class="option col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 offset-0">
                                <div class="input-group">
                                    <% if question.mcq %>
                                    <div class="input-group-prepend">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input class="form-check-input" type="checkbox" value="<%= option.id %>" name="option[<%= option.id %>]">
                                                <%= option.name %>
                                                <span class="form-check-sign">
                                                    <span class="check"></span>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                    <% else %>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="question[<%= question.id %>]" id="option<%= option.id %>" value="<%= option.id %>" <% if opt_id==0 %>required
                                            <% end %>>
                                            <%= option.name %>
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                    <% end %>
                                </div>
                            </div>
                            <% end %>
                        </div>
                        <div class="step-actions">
                            <button class=" waves-dark btn blue next-step">CONTINUE</button>
                            <% if id != 0 %>
                            <button class=" waves-dark btn btn-link previous-step">BACK</button>
                            <% end %>
                        </div>
                    </div>
                </li>
                <% end %>
                <li class="step">
                    <div class="step-title  waves-dark">
                        <%= t('surveys.labels.finished') %>
                    </div>
                    <div class="step-content">
                        <% if current_user.man? %>
                        <%= t('surveys.labels.thanks.male', name: current_user.fullname) %>
                        <% elsif current_user.woman? %>
                        <%= t('surveys.labels.thanks.female', name: current_user.fullname) %>
                        <% end %>
                        <div class="step-actions">
                            <%= f.submit t('surveys.submit'), :disable_with => 'Submiting...', class: "waves-dark btn blue" %>
                        </div>
                    </div>
                </li>
            </ul>
            <% end %>
        </div>
    </div>
</div>
<section class="my-5">
    <div class="card-body p-0">
        <%= render 'comments/new', comment: Comment.build_from( @survey, current_user.id, '' ), item: @survey, item_id: @survey.id, item_type: 'survey' %>
        <section id="survey-<%= @survey.id %>-comments" class="comments">
            <%= render 'comments/index', comments: @survey.comments, defcon: 0 %>
        </section>
    </div>
</section>
<script type="text/javascript">
var stepper = document.querySelector('.stepper');
var stepperInstace = new MStepper(stepper, {
    // Default active step.
    firstActive: 0,
    // Allow navigation by clicking on the next and previous steps on linear steppers.
    linearStepsNavigation: true,
    // Auto focus on first input of each step.
    autoFocusInput: true,
    // Set if a loading screen will appear while feedbacks functions are running.
    showFeedbackPreloader: true,
    // Auto generation of a form around the stepper.
    autoFormCreation: true,
    // Function to be called everytime a nextstep occurs. It receives 2 arguments, in this sequece: stepperForm, activeStepContent.
    // validationFunction: defaultValidationFunction, // more about this default functions below
    // Enable or disable navigation by clicking on step-titles
    stepTitleNavigation: true,
    // Preloader used when step is waiting for feedback function. If not defined, Materializecss spinner-blue-only will be used.
    feedbackPreloader: '<div class="spinner-layer spinner-blue-only">...</div>'
})
</script>
<% end %>